# -*- coding: utf-8 -*-
"""UAS_Pembelajaran_Mesin_Topik_3_MBG2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqAPgL1S45ymKQXJw10Cx1-T1-_hqGpJ

Tugas UAS Pembelajaran Mesin

Topik ke 3

Tema MBG (500) rows

Nama Anggota:

WINNI NUR RAHMAWATI (2411502020)

ADELIA ZAHWA BILQIST (2411502087)
"""

!npx playwright install --with-deps

twitter_auth_token = '34f51faa77b9678b1c82098b957a7f02403a9514'
# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

# Install missing dependency for Playwright
!sudo apt-get install -y libatk1.0-0

# Crawl Data

filename = 'MBG_2026.csv'
search_keyword = 'makan bergizi gratis OR MBG lang:id'
limit = 500

!npx -y tweet-harvest@2.7.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

import pandas as pd
import re
import string

file_path = '/content/MBG_2026 (1).xlsx'
df = pd.read_excel(file_path)

print("Original DataFrame Info:")
df.info()
display(df.head())

"""### Data Cleaning and Preprocessing"""

# Remove duplicate rows
df.drop_duplicates(inplace=True)
print(f"DataFrame after removing duplicates: {df.shape[0]} rows")

# Drop any rows where 'full_text' might be missing (if applicable, though unlikely for tweets)
df.dropna(subset=['full_text'], inplace=True)
print(f"DataFrame after dropping rows with missing 'full_text': {df.shape[0]} rows")

display(df.head())

# Define a function to clean text
def clean_text(text):
    text = text.lower() # Lowercase the text
    text = re.sub(r'http\S+', '', text) # Remove URLs
    text = re.sub(r'@\w+', '', text) # Remove mentions
    text = re.sub(r'#\w+', '', text) # Remove hashtags
    text = text.translate(str.maketrans('', '', string.punctuation)) # Remove punctuation
    text = re.sub(r'\d+', '', text) # Remove numbers
    text = re.sub(r'\s+', ' ', text).strip() # Remove extra spaces
    # Hapus emoji
    text = re.sub(r'[\U00010000-\U0010ffff]', '', text)

    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = re.sub(r'\s+', ' ', text).strip()
    return text


# Apply the cleaning function to the 'full_text' column
df['cleaned_text'] = df['full_text'].apply(clean_text)

print("DataFrame with cleaned text:")
display(df[['full_text', 'cleaned_text']].head())

from google.colab import files

# Ambil hanya kolom cleaned_text
cleaned_df = df[['cleaned_text']]

# Simpan ke CSV
cleaned_df.to_csv('cleaned_text.csv', index=False, encoding='utf-8-sig')

# Download
files.download('cleaned_text.csv')

import pandas as pd
import re

# baca file
df = pd.read_excel("MBG_2026 (1).xlsx")

# bersihkan enter/newline/tab
df["full_text"] = (
    df["full_text"]
    .astype(str)
    .str.replace(r'[\r\n\t]+', ' ', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

# format @username###tweet
df["tweet_format"] = (
    "@" +
    df["username"].astype(str).str.strip() +
    "###" +
    df["full_text"]
)

# simpan txt
with open("lda_input.txt", "w", encoding="utf-8") as f:
    for row in df["tweet_format"]:
        f.write(row + "\n")

print("Selesai")

"""LDA (Topik Modelling)"""

!pip install gensim
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import re
import numpy as np
import pandas as pd
import gensim
import nltk
from nltk.stem.snowball import SnowballStemmer
from gensim.corpora import Dictionary, MmCorpus
from gensim.models import ldamodel
from sklearn.cluster import KMeans
from sklearn.manifold import MDS
from sklearn.decomposition import PCA

def load_dataset(filename):
    file = open(filename, 'r')
    acc_names = []
    tweets = []
    for line in file:
        line = line.strip()
        parts = line.split('###')
        acc_names.append(parts[0])
        tweets.append(parts[1])
    return acc_names, tweets

# config variables
num_topics=4

!pip install Sastrawi
import nltk
nltk.download('stopwords')
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()
stopwords = nltk.corpus.stopwords.words('indonesian')

def preprocess(text):
    # tokenizing and lowercasing
    tokens = [word.lower() for word in text.split()]
    filtered_tokens = []
    # buat yang bukan terdiri dari alfabet, dan merupakan stopword
    for token in tokens:
        if re.search('[a-zA-Z]', token) and (token not in stopwords):
            filtered_tokens.append(token)
    # lakukan stemming dengan Sastrawi stemmer
    stems = [stemmer.stem(t) for t in filtered_tokens]
    return stems

# Kita load dokumen twitter, dan lakukan preprocessing terhadap tweet yang sudah di-load
acc_names, tweets = load_dataset("lda_input.txt")
print(acc_names)
print(tweets)
# Lakukan pre-process untuk setiap tweet pada koleksi "tweets" kita
# Gunakan List Comprehension untuk mempermudah hidup kita
tweets = [preprocess(tweet) for tweet in tweets]
print(tweets)

from gensim.corpora import Dictionary

# Membuat Dictionary
dictionary = Dictionary(tweets)

print("Jumlah kata sebelum filtering :", len(dictionary))

# Filter kata
dictionary.filter_extremes(
    no_below=5,      # kata muncul minimal di 5 dokumen
    no_above=0.5     # buang kata yang muncul di >50% dokumen
)

print("Jumlah kata setelah filtering :", len(dictionary))

# Membuat Corpus (Bag of Words)
corpus = [dictionary.doc2bow(tweet) for tweet in tweets]

print(corpus[:5])

# Run the LDA !
lda = ldamodel.LdaModel(corpus, num_topics=num_topics, id2word=dictionary, random_state=1, iterations=10000)

# tampilkan topic matrix
topics_matrix = lda.show_topics(formatted=False)
for topic_no, topic_words in topics_matrix:
    print ('topic number: {}'.format(topic_no))
    # default: top-10 kata yang paling tinggi probabilitasnya
    for word, prob in topic_words:
        print (word, prob)

# bentuk terlebih dahulu vektor dokumen/tweet
# vektor tweet/dokumen = vektor probabilitas terhadap masing-masing topik
tweet_vectors = []
for i, tweet_bow in enumerate(corpus): # Iterate over the corpus (bag-of-words representation)
    # Get topic probabilities for the current document.
    # Setting minimum_probability=0.0 ensures all topics are considered.
    doc_topic_distribution = lda.get_document_topics(tweet_bow, minimum_probability=0.0)

    # Initialize a vector for the current tweet with zeros for all topics
    probs_vector = [0.0] * num_topics

    # Fill the probs_vector with the actual probabilities
    for topic_id, prob in doc_topic_distribution:
        if topic_id < num_topics: # Ensure topic_id is within expected bounds
            probs_vector[topic_id] = prob
    tweet_vectors.append(probs_vector)

tweet_vectors = np.array(tweet_vectors)
# kita set banyaknya cluster = banyaknya topik
num_clusters = num_topics
# gunakan algoritma K-Means, dan lakukan clustering !
km = KMeans(n_clusters=num_clusters, random_state=42, n_init='auto')
km.fit(tweet_vectors)
# jika kita ingin melihat indeks cluster untuk setiap tweet/dokumen
clusters = km.labels_.tolist()
print(clusters)

order_centroids = km.cluster_centers_.argsort()[:, ::-1]
cluster_names = {}
for i in range(num_clusters):
    print ("cluster %d words:" % i)

    # ambil 2 topik major untuk setiap cluster
    topic_words = []
    for ind in order_centroids[i, :1]:
            topic_words += [dictionary.get(word_id) for (word_id, prob) in lda.get_topic_terms(ind, topn=2)]

    cluster_names[i] = ','.join(topic_words)
    print (cluster_names[i])

import numpy as np
from collections import Counter

cluster_names = {}

for cluster_id in range(num_clusters):

    print("="*60)
    print(f"CLUSTER {cluster_id}")

    # Ambil indeks dokumen yang termasuk cluster ini
    doc_index = np.where(np.array(clusters) == cluster_id)[0]

    # Ambil topik dominan setiap dokumen
    dominant_topics = []

    for idx in doc_index:

        topic = max(
            lda.get_document_topics(corpus[idx]),
            key=lambda x: x[1]
        )[0]

        dominant_topics.append(topic)

    # Cari topik yang paling sering muncul di cluster
    major_topic = Counter(dominant_topics).most_common(1)[0][0]

    # Ambil 5 kata teratas dari topik tersebut
    topic_words = [
        word
        for word, prob in lda.show_topic(major_topic, topn=5)
    ]

    cluster_names[cluster_id] = ", ".join(topic_words)

    print("Topik Dominan :", major_topic)
    print("Kata Kunci    :", cluster_names[cluster_id])

### plot ke 2D ###
#reduksi dimensi dengan multidimensional scaling
mds = MDS(n_components=2)
pos = mds.fit_transform(tweet_vectors) # shape (n_components, n_samples)
#pca = PCA(n_components=2)
#pos = pca.fit_transform(tweet_vectors) # shape (n_components, n_samples)
# ambil hasil reduksi ke 2D untuk posisi x dan y --> agar bisa di-plot di bidang kartesius
xs, ys = pos[:, 0], pos[:, 1]

# fungsi yang digunakan untuk plot cluster dokumen berdsarkan distribusi topik yang dimilikinya
# xs adalah posisi axis dari semua dokumen (numpy list of real number)
# ys adalah posisi ordinat dari semua dokumen (numpy list of real number)
# clusters adalah list dari cluster index untuk masing-masing dokumen
# acc_names adalah list dari nama-nama dokumen (dalam hal ini, nama-nama akun tweet)
def plot_doc_cluster(xs, ys, clusters, acc_names):
    # warna cluster - maksimal 5 cluster
    cluster_colors = {0: '#1b9e77', 1: '#d95f02', 2: '#7570b3', 3: '#e7298a', 4: '#66a61e'}
    # gunakan Pandas untuk kemudahan proses data, terutama untuk grouping
    df = pd.DataFrame(dict(x=xs, y=ys, label=clusters, acc_names=acc_names))
    groups = df.groupby('label') #group by cluster!!!
    fig, ax = plt.subplots(figsize=(17, 9)) # set size
    ax.margins(0.05)
    for name, group in groups:
        ax.plot(group.x, group.y, marker='o', linestyle='', ms=12, label=cluster_names[name], color=cluster_colors[name], mec='none')
        ax.set_aspect('auto')
        ax.tick_params(axis= 'x', which='both', bottom='off', top='off', labelbottom='off')
        ax.tick_params(axis= 'y', which='both', left='off', top='off', labelleft='off')
    ax.legend(numpoints=1) #show legend with only 1 point
    for i in range(len(df)):
        ax.text(df.iloc[i]['x'], df.iloc[i]['y'], df.iloc[i]['acc_names'], size=8)
    plt.show()
# fungsi yang digunakan untuk plot distribusi kata per-topik yang ditemukan
def plot_word_dist_per_topic(topic_no, topics_matrix, width=0.5):
    _, topic_words = topics_matrix[topic_no]
    # hanya top-10 yang paling tinggi probabilitasnya
    words = []
    probs = []
    for word, prob in topic_words:
        words.append(word)
        probs.append(prob)
    ind = np.arange(len(words))
    plt.bar(ind, probs, width=width)
    plt.xticks(ind + width/2, words, rotation='vertical')
    plt.title('Word Distribution of Topic {}'.format(topic_no))
    plt.show

# plot cluster dokumen/tweet
plot_doc_cluster(xs, ys, clusters, acc_names)

"""Representasi Topik"""

import numpy as np

tweet_vectors = []

for tweet_bow in corpus:

    # Probabilitas setiap topik pada satu dokumen
    topic_distribution = lda.get_document_topics(
        tweet_bow,
        minimum_probability=0.0
    )

    # Membuat vektor probabilitas
    vector = np.zeros(num_topics)

    for topic_id, prob in topic_distribution:
        vector[topic_id] = prob

    tweet_vectors.append(vector)

tweet_vectors = np.array(tweet_vectors)

print(tweet_vectors.shape)

print("===== HASIL TOPIK LDA =====")

for i in range(num_topics):
    print(f"\nTopik {i}")
    print(lda.print_topic(i, topn=10))

# Initialize an empty list to store the dominant topic for each document
all_dominant_topics = []

# Iterate through each document's bag-of-words representation in the corpus
for doc_bow in corpus:
    # Get the topic distribution for the current document
    # minimum_probability=0.0 ensures all topics are considered, even if very low probability
    topic_distribution = lda.get_document_topics(doc_bow, minimum_probability=0.0)

    # Find the topic with the highest probability
    # topic_distribution is a list of tuples (topic_id, probability)
    # The max function with key=lambda x: x[1] finds the tuple with the highest probability value
    dominant_topic_id = max(topic_distribution, key=lambda x: x[1])[0]

    # Append the dominant topic ID to our list
    all_dominant_topics.append(dominant_topic_id)

# Assign the list of dominant topics to the 'topic' column in the DataFrame
df["topic"] = all_dominant_topics

df.to_excel("hasil_LDA_KMeans.xlsx", index=False)

from google.colab import files
files.download("hasil_LDA_KMeans.xlsx")

"""Clustering FTC

Clustering menggunakan Frequent Term Based Clustering (FTC). Kandidat cluster dibentuk dari frequent term/term-set, lalu dipilih iteratif memakai nilai Entropy Overlap (EO) minimum
"""

import pandas as pd

df = pd.read_csv("/content/cleaned_text (1).csv")

from itertools import combinations
from collections import Counter
from typing import Sequence
import numpy as np
import pandas as pd

FTC_MIN_SUPPORT = 8
FTC_MAX_K = 2
FTC_MAX_TERMS = 120


def generate_frequent_termsets(
    token_lists: Sequence[Sequence[str]],
    min_support: int = 8,
    max_k: int = 2,
    max_terms: int = 120,
) -> dict[tuple[str, ...], set[int]]:
    doc_terms = [set(tokens) for tokens in token_lists]
    doc_freq = Counter()

    for terms in doc_terms:
        doc_freq.update(terms)

    frequent_terms = [term for term, count in doc_freq.most_common(max_terms) if count >= min_support]
    frequent_term_set = set(frequent_terms)
    candidate_counts = Counter()

    for terms in doc_terms:
        filtered_terms = sorted(terms & frequent_term_set)
        for k in range(1, max_k + 1):
            if len(filtered_terms) < k:
                continue
            for termset in combinations(filtered_terms, k):
                candidate_counts[termset] += 1

    candidates = {
        termset: {
            doc_id
            for doc_id, terms in enumerate(doc_terms)
            if set(termset).issubset(terms)
        }
        for termset, support in candidate_counts.items()
        if support >= min_support
    }

    return candidates


def entropy_overlap(candidate_docs: set[int], doc_candidate_frequency: Counter[int]) -> float:
    value = 0.0
    for doc_id in candidate_docs:
        freq = doc_candidate_frequency[doc_id]
        if freq > 1:
            value += np.log(freq) / freq
    return float(value)


def ftc_clustering(
    token_lists: Sequence[Sequence[str]],
    min_support: int = 8,
    max_k: int = 2,
    max_terms: int = 120,
) -> tuple[np.ndarray, pd.DataFrame]:
    candidates = generate_frequent_termsets(
        token_lists,
        min_support=min_support,
        max_k=max_k,
        max_terms=max_terms,
    )

    labels = np.full(len(token_lists), -1, dtype=int)
    remaining_docs = set(range(len(token_lists)))
    selected_rows = []
    cluster_id = 0
    iteration = 1

    while candidates and remaining_docs:
        active_candidates = {
            termset: docs & remaining_docs
            for termset, docs in candidates.items()
        }
        active_candidates = {
            termset: docs
            for termset, docs in active_candidates.items()
            if len(docs) >= min_support
        }

        if not active_candidates:
            break

        doc_candidate_frequency = Counter()
        for docs in active_candidates.values():
            doc_candidate_frequency.update(docs)

        scored_candidates = []
        for termset, docs in active_candidates.items():
            eo_value = entropy_overlap(docs, doc_candidate_frequency)
            scored_candidates.append((eo_value, -len(docs), -len(termset), termset, docs))

        eo_value, neg_support, neg_len, best_termset, best_docs = min(scored_candidates)
        support = len(best_docs)

        labels[list(best_docs)] = cluster_id
        selected_rows.append(
            {
                "iteration": iteration,
                "cluster_id": cluster_id,
                "frequent_termset": ", ".join(best_termset),
                "support": support,
                "entropy_overlap": round(eo_value, 6),
                "n_remaining_docs_after": len(remaining_docs - best_docs),
            }
        )

        remaining_docs -= best_docs
        cluster_id += 1
        iteration += 1

    if remaining_docs:
        residual_cluster_id = cluster_id
        labels[list(remaining_docs)] = residual_cluster_id
        selected_rows.append(
            {
                "iteration": iteration,
                "cluster_id": residual_cluster_id,
                "frequent_termset": "RESIDUAL_UNASSIGNED",
                "support": len(remaining_docs),
                "entropy_overlap": 0.0,
                "n_remaining_docs_after": 0,
            }
        )

    return labels, pd.DataFrame(selected_rows)


def topic_label(topic_words_df: pd.DataFrame, topic_id: int, n_words: int = 5) -> str:
    words = (
        topic_words_df.loc[topic_words_df["topic_id"] == topic_id]
        .sort_values("rank")
        .head(n_words)["term"]
        .tolist()
    )
    return ", ".join(words)


def make_cluster_summary(
    comments_df: pd.DataFrame,
    topic_words_df: pd.DataFrame,
    token_lists: Sequence[Sequence[str]],
    ftc_selected_clusters: pd.DataFrame,
) -> pd.DataFrame:
    rows = []
    termset_lookup = dict(
        zip(ftc_selected_clusters["cluster_id"], ftc_selected_clusters["frequent_termset"])
    )
    eo_lookup = dict(
        zip(ftc_selected_clusters["cluster_id"], ftc_selected_clusters["entropy_overlap"])
    )

    for cluster_id, group in comments_df.groupby("cluster_id"):
        dominant_topic = int(group["topic_id"].mode().iloc[0])
        token_counter = Counter()

        for index in group.index:
            token_counter.update(token_lists[index])

        rows.append(
            {
                "cluster_id": int(cluster_id),
                "n_comments": int(len(group)),
                "ftc_termset": termset_lookup.get(int(cluster_id), ""),
                "entropy_overlap": eo_lookup.get(int(cluster_id), 0.0),
                "dominant_topic": dominant_topic,
                "dominant_topic_terms": topic_label(topic_words_df, dominant_topic),
                "cluster_top_terms": ", ".join(term for term, _ in token_counter.most_common(10)),
                "example_comment": str(group[TEXT_COL].iloc[0]),
            }
        )

    return pd.DataFrame(rows).sort_values("cluster_id").reset_index(drop=True)

token_lists = tweets
lda_model = lda
N_TOPICS = num_topics

# Create topic_words DataFrame from LDA model output
topic_words_data = []
for topic_id, word_probs in lda_model.show_topics(formatted=False, num_topics=N_TOPICS):
    for i, (word, prob) in enumerate(word_probs):
        topic_words_data.append({"topic_id": topic_id, "term": word, "rank": i, "probability": prob})
topic_words = pd.DataFrame(topic_words_data)

cluster_labels, ftc_selected_clusters = ftc_clustering(
    token_lists,
    min_support=FTC_MIN_SUPPORT,
    max_k=FTC_MAX_K,
    max_terms=FTC_MAX_TERMS,
)

# The 'tokens' column does not exist in the current df, so remove the drop operation.
result_df = df.copy()
# Use already computed all_dominant_topics for topic_id
result_df["topic_id"] = all_dominant_topics
# Use tweet_vectors for topic_confidence
result_df["topic_confidence"] = tweet_vectors.max(axis=1).round(4)
result_df["cluster_id"] = cluster_labels

for topic_id in range(N_TOPICS):
    # Use tweet_vectors for individual topic probabilities
    result_df[f"topic_{topic_id}_prob"] = tweet_vectors[:, topic_id].round(4)

# Define TEXT_COL for the make_cluster_summary function
TEXT_COL = 'cleaned_text'

cluster_summary = make_cluster_summary(
    result_df,
    topic_words,
    token_lists,
    ftc_selected_clusters,
)

print("Jumlah cluster FTC:", result_df["cluster_id"].nunique())
print("Min support FTC:", FTC_MIN_SUPPORT)
print("Max k termset:", FTC_MAX_K)
cluster_summary

result_df[[TEXT_COL, "cleaned_text", "topic_id", "topic_confidence", "cluster_id"]].head(20)

from pathlib import Path

OUTPUT_DIR = Path("output")
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

# Add 'comment_id' and 'token_count' to result_df before saving
result_df['comment_id'] = result_df.index # Using the DataFrame index as a unique ID
result_df['token_count'] = [len(tokens) for tokens in token_lists] # Calculate token count

result_df.to_csv(OUTPUT_DIR / "comment_topics_clusters.csv", index=False)

# Adjust preprocessed_columns to include the newly added columns and correct TEXT_COL
# Assuming TEXT_COL is 'cleaned_text' and 'clean_text' is a redundancy/typo
preprocessed_columns = ["comment_id", TEXT_COL, "token_count"]
result_df[preprocessed_columns].to_csv(
    OUTPUT_DIR / "comments_preprocessed.csv",
    index=False,
)

topic_words.to_csv(OUTPUT_DIR / "topic_words.csv", index=False)
# Check if topic_matrix exists before saving
if 'topic_matrix' in globals():
    topic_matrix.to_csv(OUTPUT_DIR / "topic_matrix.csv", index=False)
else:
    print("Warning: topic_matrix is not defined and will not be saved.")

cluster_summary.to_csv(OUTPUT_DIR / "cluster_summary.csv", index=False)
ftc_selected_clusters.to_csv(OUTPUT_DIR / "ftc_selected_clusters.csv", index=False)

print("Output tersimpan di:", OUTPUT_DIR.resolve())
print("- comments_preprocessed.csv")
print("- topic_words.csv")
# Only print if topic_matrix was saved
if 'topic_matrix' in globals():
    print("- topic_matrix.csv")
print("- comment_topics_clusters.csv")
print("- cluster_summary.csv")
print("- ftc_selected_clusters.csv")

"""SNA (Social Network Analysis)

Persiapan Data Gephi

EDGES
"""

import pandas as pd
import re

edges = []

for _, row in df.iterrows():

    source = str(row["username"]).strip()

    text = str(row["full_text"])

    # Ambil semua akun yang di-mention
    mentions = re.findall(r'@([A-Za-z0-9_]+)', text)

    for target in mentions:

        target = target.strip()

        # Hindari self mention
        if source.lower() != target.lower():

            edges.append([source, target])

edges_df = pd.DataFrame(
    edges,
    columns=["Source","Target"]
)

edges_df = edges_df.drop_duplicates()

edges_df.to_csv(
    "edges.csv",
    index=False
)

print(edges_df.head())
print(f"Jumlah edges : {len(edges_df)}")

"""NODES"""

import pandas as pd

edges_df = pd.read_csv("edges.csv")

nodes = pd.unique(
    pd.concat(
        [
            edges_df["Source"],
            edges_df["Target"]
        ],
        ignore_index=True
    )
)

nodes_df = pd.DataFrame({
    "Id": nodes,
    "Label": nodes
})

nodes_df.to_csv(
    "nodes.csv",
    index=False
)

print(nodes_df.head())
print(f"Jumlah Nodes : {len(nodes_df)}")

"""Load Graph"""

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

# Load data
edges = pd.read_csv("edges.csv")

# Membuat graph
G = nx.from_pandas_edgelist(
    edges,
    source="Source",
    target="Target",
    create_using=nx.Graph()
)

print("Jumlah Node :", G.number_of_nodes())
print("Jumlah Edge :", G.number_of_edges())

"""Hitung SNA"""

import pandas as pd

degree = nx.degree_centrality(G)
betweenness = nx.betweenness_centrality(G)
closeness = nx.closeness_centrality(G)
eigenvector = nx.eigenvector_centrality(G, max_iter=1000)

hasil_sna = pd.DataFrame({
    "Node": list(degree.keys()),
    "Degree": list(degree.values()),
    "Betweenness": [betweenness[n] for n in degree.keys()],
    "Closeness": [closeness[n] for n in degree.keys()],
    "Eigenvector": [eigenvector[n] for n in degree.keys()]
})

hasil_sna = hasil_sna.sort_values(
    by="Degree",
    ascending=False
)
hasil_sna.to_excel(
    "hasil_SNA.xlsx",
    index=False
)

print("Berhasil disimpan")

hasil_sna.head()

"""Visualisasi Network"""

plt.figure(figsize=(12,10))

pos = nx.spring_layout(G, seed=42)

nx.draw_networkx_nodes(
    G,
    pos,
    node_size=40
)

nx.draw_networkx_edges(
    G,
    pos,
    alpha=0.3
)

plt.title("Social Network Analysis")
plt.axis("off")
plt.show()

"""Community Detection"""

!pip install python-louvain
from community import community_louvain
import pandas as pd
import networkx as nx

# Menjalankan algoritma Louvain
partition = community_louvain.best_partition(G)

# Lihat beberapa hasil
for i, (node, comm) in enumerate(partition.items()):
    print(node, "-> Community", comm)
    if i == 10:
        break

community_df = pd.DataFrame({
    "Node": list(partition.keys()),
    "Community": list(partition.values())
})

community_df.head()

community_df.to_excel(
    "hasil_community_detection.xlsx",
    index=False
)

print("Hasil Community Detection berhasil disimpan.")

"""Visualisasi Community Detection"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14,10))

pos = nx.spring_layout(G, seed=42)

communities = list(partition.values())

nx.draw_networkx_nodes(
    G,
    pos,
    node_color=communities,
    cmap=plt.cm.Set3,
    node_size=60
)

nx.draw_networkx_edges(
    G,
    pos,
    alpha=0.3
)

plt.title("Community Detection (Louvain)")
plt.axis("off")
plt.show()

"""Hitung Jumlah Community"""

jumlah_community = community_df["Community"].nunique()

print("Jumlah Community :", jumlah_community)

print("\nJumlah Anggota Tiap Community")

community_df["Community"].value_counts().sort_index()

community_df["Node"] = community_df["Node"].str.replace("@","")

integrasi = df.merge(
    community_df,
    left_on="username",
    right_on="Node",
    how="left"
)

"""Integrasi"""

integrasi["Topic"] = all_dominant_topics
integrasi["Cluster"] = clusters

hasil_akhir = integrasi[
    [
        "username",
        "full_text",
        "Topic",
        "Cluster",
        "Community"
    ]
]

hasil_akhir.head()

hasil_akhir.to_excel(
    "hasil_integrasi.xlsx",
    index=False
)

print("Integrasi berhasil")

"""INTERPRETASI

"""

from collections import Counter
import pandas as pd

print("="*80)
print("HASIL INTERPRETASI")
print("="*80)

interpretasi = []

for cluster in sorted(hasil_akhir["Cluster"].unique()):

    # Ambil data tiap cluster
    data_cluster = hasil_akhir[
        hasil_akhir["Cluster"] == cluster
    ]

    topic_dominan = (
        data_cluster["Topic"]
        .value_counts()
        .idxmax()
    )

    keywords = [
        word
        for word, prob in lda.show_topic(
            topic_dominan,
            topn=5
        )
    ]

    if data_cluster["Community"].dropna().shape[0] > 0:
        community = (
            data_cluster["Community"]
            .dropna()
            .astype(int)
            .value_counts()
            .idxmax()
        )
    else:
        community = "Tidak ada"
    jumlah = len(data_cluster)

    interpretasi.append([
        cluster,
        topic_dominan,
        ", ".join(keywords),
        community,
        jumlah
    ])

    print(f"\nCLUSTER {cluster}")
    print(f"Jumlah Tweet     : {jumlah}")
    print(f"Topic Dominan    : Topic {topic_dominan}")
    print(f"Kata Kunci       : {', '.join(keywords)}")
    print(f"Community Dominan: {community}")

interpretasi_df = pd.DataFrame(
    interpretasi,
    columns=[
        "Cluster",
        "Topic Dominan",
        "Kata Kunci",
        "Community Dominan",
        "Jumlah Tweet"
    ]
)

interpretasi_df.to_excel(
    "hasil_interpretasi.xlsx",
    index=False
)

print("\nInterpretasi berhasil disimpan.")

print("Jumlah Community:", community_df["Community"].nunique())
print(community_df["Community"].value_counts().head(10))

hasil_akhir["Community"].value_counts()

for cluster in sorted(hasil_akhir["Cluster"].unique()):
    print("="*60)
    print(f"Cluster {cluster}")

    data_cluster = hasil_akhir[hasil_akhir["Cluster"] == cluster]

    print("\nDistribusi Community:")
    print(data_cluster["Community"].value_counts())